using System;
using System.Collections.Generic;
using System.Windows;

namespace DesktopPlus
{
    public partial class MainWindow : Window
    {
        private static readonly Dictionary<string, Dictionary<string, string>> LocalizationData =
            new Dictionary<string, Dictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
            {
                ["de"] = new Dictionary<string, string>
                {
                    ["Loc.TabGeneral"] = "Allgemein",
                    ["Loc.TabPanels"] = "Panels",
                    ["Loc.TabLayouts"] = "Layouts",
                    ["Loc.TabThemes"] = "Themen",
                    ["Loc.TabShortcuts"] = "Shortcuts",
                    ["Loc.GeneralTitle"] = "Allgemein",
                    ["Loc.GeneralLanguageLabel"] = "Sprache",
                    ["Loc.LanguageGerman"] = "Deutsch",
                    ["Loc.LanguageEnglish"] = "Englisch",
                    ["Loc.GeneralStartupCheckbox"] = "Mit Windows starten",
                    ["Loc.GeneralCloseLabel"] = "Beim Schließen",
                    ["Loc.CloseBehaviorMinimize"] = "Minimieren",
                    ["Loc.CloseBehaviorExit"] = "Programm beenden",
                    ["Loc.PanelsTitle"] = "Panels",
                    ["Loc.PanelsNew"] = "Neues Panel",
                    ["Loc.PanelsDesc"] = "Übersicht pro Panel.",
                    ["Loc.PanelsHide"] = "Ausblenden",
                    ["Loc.PanelsShow"] = "Einblenden",
                    ["Loc.PanelsShowAll"] = "Alle zeigen",
                    ["Loc.PanelsHideAll"] = "Alle ausblenden",
                    ["Loc.PanelsDelete"] = "Löschen",
                    ["Loc.PanelsSettings"] = "Einstellungen",
                    ["Loc.PanelDropHint"] = "Ordner hierher ziehen um Standardordner zu setzen\noder Dateien ablegen",
                    ["Loc.PanelDropHintShort"] = "Dateien oder Ordner hierher ziehen",
                    ["Loc.LayoutsTitle"] = "Layouts",
                    ["Loc.LayoutsCreateFromCurrent"] = "Layout hinzufügen",
                    ["Loc.LayoutsCreateEmpty"] = "Leeres Layout",
                    ["Loc.LayoutsDesc"] = "Layouts speichern sichtbare Panels, Positionen und Theme.",
                    ["Loc.LayoutsApply"] = "Laden",
                    ["Loc.LayoutsUpdate"] = "Aktuelles Layout speichern",
                    ["Loc.LayoutsDelete"] = "Löschen",
                    ["Loc.LayoutsDefaultPreset"] = "Standard-Preset",
                    ["Loc.ThemesTitle"] = "Preset-Auswahl",
                    ["Loc.ThemesDesc"] = "Wähle ein Preset oder speichere dein aktuelles Theme.",
                    ["Loc.ThemesPresetTooltip"] = "Neues Preset",
                    ["Loc.ThemesApplyAll"] = "Auf alle",
                    ["Loc.ThemesSave"] = "Speichern",
                    ["Loc.ThemesDelete"] = "Löschen",
                    ["Loc.ThemesResetDefaults"] = "Standard-Presets",
                    ["Loc.FineTuneTitle"] = "Feintuning",
                    ["Loc.LabelBackgroundColor"] = "Hintergrundfarbe",
                    ["Loc.LabelHeaderColor"] = "Header-Farbe",
                    ["Loc.LabelOpacity"] = "Deckkraft",
                    ["Loc.LabelAccentColor"] = "Akzentfarbe",
                    ["Loc.TypographyTitle"] = "Typografie",
                    ["Loc.LabelFontFamily"] = "Schriftart",
                    ["Loc.LabelTextColor"] = "Textfarbe",
                    ["Loc.LabelFolderColor"] = "Ordnerfarbe",
                    ["Loc.LabelTitleSize"] = "Titelgröße",
                    ["Loc.LabelItemSize"] = "Textgröße",
                    ["Loc.LabelCornerRadius"] = "Eckenradius",
                    ["Loc.LabelShadow"] = "Schatten",
                    ["Loc.LabelMode"] = "Modus",
                    ["Loc.ModeSolid"] = "Farbe",
                    ["Loc.ModeImage"] = "Bild",
                    ["Loc.ModePattern"] = "Muster",
                    ["Loc.LabelPattern"] = "Muster",
                    ["Loc.PatternNone"] = "Keine",
                    ["Loc.PatternDiagonal"] = "Diagonal",
                    ["Loc.PatternGrid"] = "Karos",
                    ["Loc.PatternDots"] = "Punkte",
                    ["Loc.LabelBackgroundImage"] = "Hintergrundbild",
                    ["Loc.ButtonBrowse"] = "...",
                    ["Loc.OptionGlass"] = "Glass-Effekt",
                    ["Loc.OptionImageFill"] = "Bild füllen",
                    ["Loc.LabelImageGlassIntensity"] = "Bild/Glass Intensität",
                    ["Loc.PreviewTitle"] = "Vorschau",
                    ["Loc.PreviewFolderDocs"] = "Dokumente",
                    ["Loc.PreviewFolderPhotos"] = "Bilder",
                    ["Loc.PreviewFolderProjects"] = "Projekte",
                    ["Loc.PreviewFileReadme"] = "readme.md",
                    ["Loc.PreviewFileTodo"] = "todo.txt",
                    ["Loc.PreviewFileBudget"] = "Budget.xlsx",
                    ["Loc.ShortcutsTitle"] = "Shortcuts",
                    ["Loc.ShortcutsDesc"] = "Globale Hotkeys für Panels und Layouts kommen bald.",
                    ["Loc.PanelStateOpen"] = "Offen",
                    ["Loc.PanelStateCollapsed"] = "Eingeklappt",
                    ["Loc.PanelStateHidden"] = "Ausgeblendet",
                    ["Loc.PanelStateClosed"] = "Geschlossen",
                    ["Loc.PanelTypeList"] = "Liste ({0})",
                    ["Loc.PanelActionFocus"] = "Fokussieren",
                    ["Loc.PanelActionShow"] = "Anzeigen",
                    ["Loc.PanelActionReveal"] = "Einblenden",
                    ["Loc.PanelCount"] = "{0} Panels",
                    ["Loc.PanelCountHidden"] = "{0} Panels, {1} ausgeblendet",
                    ["Loc.LayoutCount"] = "{0} Layouts",
                    ["Loc.LayoutSummaryEmpty"] = "Leer",
                    ["Loc.LayoutSummaryVisibleHidden"] = "{0} sichtbar, {1} ausgeblendet",
                    ["Loc.LayoutSummaryTheme"] = "Theme",
                    ["Loc.Untitled"] = "Unbenannt",
                    ["Loc.NoFolder"] = "(kein Ordner)",
                    ["Loc.PanelWindowTitle"] = "Panel",
                    ["Loc.PanelDefaultTitle"] = "Panel",
                    ["Loc.PanelMoveTooltip"] = "Fenster verschieben",
                    ["Loc.PanelSettingsTooltip"] = "Panel-Einstellungen",
                    ["Loc.PanelSearchPlaceholder"] = "Suchen...",
                    ["Loc.PanelCollapseTooltip"] = "Inhalt ein-/ausklappen",
                    ["Loc.PanelCloseTooltip"] = "Schließen",
                    ["Loc.PanelSettingsTitle"] = "Panel-Einstellungen",
                    ["Loc.PanelSettingsName"] = "Name",
                    ["Loc.PanelSettingsPreset"] = "Preset",
                    ["Loc.PanelSettingsDefaultFolder"] = "Standardordner",
                    ["Loc.PanelSettingsFolderUnset"] = "(nicht gesetzt)",
                    ["Loc.PanelSettingsChange"] = "Ändern",
                    ["Loc.PanelSettingsFolderAction"] = "Ordner-Aktion",
                    ["Loc.PanelSettingsOpenInternal"] = "Im Panel navigieren",
                    ["Loc.PanelSettingsOpenExternal"] = "Im Explorer öffnen",
                    ["Loc.PanelSettingsExpandOnHover"] = "Beim Hover aufklappen",
                    ["Loc.PanelSettingsShowHidden"] = "Versteckte Elemente anzeigen",
                    ["Loc.PanelSettingsShowSettingsButton"] = "Einstellungsbutton anzeigen",
                    ["Loc.PanelSettingsMovement"] = "Bewegung",
                    ["Loc.MovementTitlebar"] = "Titelleiste ziehen",
                    ["Loc.MovementButton"] = "Move-Button",
                    ["Loc.MovementLocked"] = "Gesperrt",
                    ["Loc.PanelSettingsCancel"] = "Abbrechen",
                    ["Loc.PanelSettingsSave"] = "Speichern",
                    ["Loc.InputDialogTitle"] = "Eingabe",
                    ["Loc.InputDialogOk"] = "OK",
                    ["Loc.InputDialogCancel"] = "Abbrechen",
                    ["Loc.TrayOpen"] = "Öffnen",
                    ["Loc.TrayExit"] = "Beenden",
                    ["Loc.MsgError"] = "Fehler",
                    ["Loc.MsgInfo"] = "Hinweis",
                    ["Loc.MsgPresetNameRequired"] = "Bitte einen Preset-Namen eingeben.",
                    ["Loc.MsgPresetBuiltIn"] = "Ein eingebautes Preset kann nicht überschrieben werden. Wähle einen anderen Namen.",
                    ["Loc.MsgPresetBuiltInDelete"] = "Eingebaute Presets können nicht gelöscht werden.",
                    ["Loc.MsgPresetReset"] = "Standard-Presets wurden zurückgesetzt.",
                    ["Loc.MsgResetConfirmTitle"] = "Zurücksetzen bestätigen",
                    ["Loc.MsgResetConfirmMessage"] = "Möchten Sie wirklich alle Standard-Presets zurücksetzen?\n\nDiese Aktion kann nicht rückgängig gemacht werden.",
                    ["Loc.ThemesResetDefaultsFull"] = "Standard-Presets zurücksetzen",
                    ["Loc.MsgRestoreError"] = "Fehler beim Wiederherstellen der Fenster:\n{0}",
                    ["Loc.MsgSaveError"] = "Fehler beim Speichern der Fenster:\n{0}",
                    ["Loc.MsgMoveFolderError"] = "Ordner konnte nicht verschoben werden:\n{0}",
                    ["Loc.MsgMoveFileError"] = "Datei konnte nicht verschoben werden:\n{0}",
                    ["Loc.MsgOpenFolderError"] = "Fehler beim Öffnen des Ordners:\n{0}",
                    ["Loc.MsgOpenFileError"] = "Fehler beim Öffnen der Datei:\n{0}",
                    ["Loc.MsgStartupError"] = "Autostart konnte nicht aktualisiert werden:\n{0}",
                    ["Loc.PromptLayoutName"] = "Layout-Name",
                    ["Loc.PromptPanelName"] = "Panel-Name"
                },
                ["en"] = new Dictionary<string, string>
                {
                    ["Loc.TabGeneral"] = "General",
                    ["Loc.TabPanels"] = "Panels",
                    ["Loc.TabLayouts"] = "Layouts",
                    ["Loc.TabThemes"] = "Themes",
                    ["Loc.TabShortcuts"] = "Shortcuts",
                    ["Loc.GeneralTitle"] = "General",
                    ["Loc.GeneralLanguageLabel"] = "Language",
                    ["Loc.LanguageGerman"] = "German",
                    ["Loc.LanguageEnglish"] = "English",
                    ["Loc.GeneralStartupCheckbox"] = "Start with Windows",
                    ["Loc.GeneralCloseLabel"] = "On close",
                    ["Loc.CloseBehaviorMinimize"] = "Minimize",
                    ["Loc.CloseBehaviorExit"] = "Exit application",
                    ["Loc.PanelsTitle"] = "Panels",
                    ["Loc.PanelsNew"] = "New panel",
                    ["Loc.PanelsDesc"] = "Overview per panel.",
                    ["Loc.PanelsHide"] = "Hide",
                    ["Loc.PanelsShow"] = "Show",
                    ["Loc.PanelsShowAll"] = "Show all",
                    ["Loc.PanelsHideAll"] = "Hide all",
                    ["Loc.PanelsDelete"] = "Delete",
                    ["Loc.PanelsSettings"] = "Settings",
                    ["Loc.PanelDropHint"] = "Drop a folder here to set as default\nor drop individual files",
                    ["Loc.PanelDropHintShort"] = "Drop files or folders here",
                    ["Loc.LayoutsTitle"] = "Layouts",
                    ["Loc.LayoutsCreateFromCurrent"] = "Add layout",
                    ["Loc.LayoutsCreateEmpty"] = "Add empty",
                    ["Loc.LayoutsDesc"] = "Layouts store visible panels, positions, and theme.",
                    ["Loc.LayoutsApply"] = "Load",
                    ["Loc.LayoutsUpdate"] = "Save current layout",
                    ["Loc.LayoutsDelete"] = "Delete",
                    ["Loc.LayoutsDefaultPreset"] = "Default preset",
                    ["Loc.ThemesTitle"] = "Preset selection",
                    ["Loc.ThemesDesc"] = "Choose a preset or save your current theme.",
                    ["Loc.ThemesPresetTooltip"] = "New preset",
                    ["Loc.ThemesApplyAll"] = "Apply to all",
                    ["Loc.ThemesSave"] = "Save",
                    ["Loc.ThemesDelete"] = "Delete",
                    ["Loc.ThemesResetDefaults"] = "Reset defaults",
                    ["Loc.FineTuneTitle"] = "Fine tune",
                    ["Loc.LabelBackgroundColor"] = "Background color",
                    ["Loc.LabelHeaderColor"] = "Header color",
                    ["Loc.LabelOpacity"] = "Opacity",
                    ["Loc.LabelAccentColor"] = "Accent color",
                    ["Loc.TypographyTitle"] = "Typography",
                    ["Loc.LabelFontFamily"] = "Font",
                    ["Loc.LabelTextColor"] = "Text color",
                    ["Loc.LabelFolderColor"] = "Folder color",
                    ["Loc.LabelTitleSize"] = "Title size",
                    ["Loc.LabelItemSize"] = "Item size",
                    ["Loc.LabelCornerRadius"] = "Corner radius",
                    ["Loc.LabelShadow"] = "Shadow",
                    ["Loc.LabelMode"] = "Mode",
                    ["Loc.ModeSolid"] = "Solid",
                    ["Loc.ModeImage"] = "Image",
                    ["Loc.ModePattern"] = "Pattern",
                    ["Loc.LabelPattern"] = "Pattern",
                    ["Loc.PatternNone"] = "None",
                    ["Loc.PatternDiagonal"] = "Diagonal",
                    ["Loc.PatternGrid"] = "Grid",
                    ["Loc.PatternDots"] = "Dots",
                    ["Loc.LabelBackgroundImage"] = "Background image",
                    ["Loc.ButtonBrowse"] = "...",
                    ["Loc.OptionGlass"] = "Glass effect",
                    ["Loc.OptionImageFill"] = "Fill image",
                    ["Loc.LabelImageGlassIntensity"] = "Image/Glass intensity",
                    ["Loc.PreviewTitle"] = "Preview",
                    ["Loc.PreviewFolderDocs"] = "Documents",
                    ["Loc.PreviewFolderPhotos"] = "Pictures",
                    ["Loc.PreviewFolderProjects"] = "Projects",
                    ["Loc.PreviewFileReadme"] = "readme.md",
                    ["Loc.PreviewFileTodo"] = "todo.txt",
                    ["Loc.PreviewFileBudget"] = "Budget.xlsx",
                    ["Loc.ShortcutsTitle"] = "Shortcuts",
                    ["Loc.ShortcutsDesc"] = "Global hotkeys for panels and layouts are coming soon.",
                    ["Loc.PanelStateOpen"] = "Open",
                    ["Loc.PanelStateCollapsed"] = "Collapsed",
                    ["Loc.PanelStateHidden"] = "Hidden",
                    ["Loc.PanelStateClosed"] = "Closed",
                    ["Loc.PanelTypeList"] = "List ({0})",
                    ["Loc.PanelActionFocus"] = "Focus",
                    ["Loc.PanelActionShow"] = "Show",
                    ["Loc.PanelActionReveal"] = "Reveal",
                    ["Loc.PanelCount"] = "{0} panels",
                    ["Loc.PanelCountHidden"] = "{0} panels, {1} hidden",
                    ["Loc.LayoutCount"] = "{0} layouts",
                    ["Loc.LayoutSummaryEmpty"] = "Empty",
                    ["Loc.LayoutSummaryVisibleHidden"] = "{0} visible, {1} hidden",
                    ["Loc.LayoutSummaryTheme"] = "Theme",
                    ["Loc.Untitled"] = "Untitled",
                    ["Loc.NoFolder"] = "(no folder)",
                    ["Loc.PanelWindowTitle"] = "Panel",
                    ["Loc.PanelDefaultTitle"] = "Panel",
                    ["Loc.PanelMoveTooltip"] = "Move window",
                    ["Loc.PanelSettingsTooltip"] = "Panel settings",
                    ["Loc.PanelSearchPlaceholder"] = "Search...",
                    ["Loc.PanelCollapseTooltip"] = "Collapse/expand content",
                    ["Loc.PanelCloseTooltip"] = "Close",
                    ["Loc.PanelSettingsTitle"] = "Panel settings",
                    ["Loc.PanelSettingsName"] = "Name",
                    ["Loc.PanelSettingsPreset"] = "Preset",
                    ["Loc.PanelSettingsDefaultFolder"] = "Default folder",
                    ["Loc.PanelSettingsFolderUnset"] = "(not set)",
                    ["Loc.PanelSettingsChange"] = "Change",
                    ["Loc.PanelSettingsFolderAction"] = "Folder action",
                    ["Loc.PanelSettingsOpenInternal"] = "Navigate in panel",
                    ["Loc.PanelSettingsOpenExternal"] = "Open in Explorer",
                    ["Loc.PanelSettingsExpandOnHover"] = "Expand on hover",
                    ["Loc.PanelSettingsShowHidden"] = "Show hidden items",
                    ["Loc.PanelSettingsShowSettingsButton"] = "Show settings button",
                    ["Loc.PanelSettingsMovement"] = "Movement",
                    ["Loc.MovementTitlebar"] = "Drag title bar",
                    ["Loc.MovementButton"] = "Move button",
                    ["Loc.MovementLocked"] = "Locked",
                    ["Loc.PanelSettingsCancel"] = "Cancel",
                    ["Loc.PanelSettingsSave"] = "Save",
                    ["Loc.InputDialogTitle"] = "Input",
                    ["Loc.InputDialogOk"] = "OK",
                    ["Loc.InputDialogCancel"] = "Cancel",
                    ["Loc.TrayOpen"] = "Open",
                    ["Loc.TrayExit"] = "Exit",
                    ["Loc.MsgError"] = "Error",
                    ["Loc.MsgInfo"] = "Info",
                    ["Loc.MsgPresetNameRequired"] = "Please enter a preset name.",
                    ["Loc.MsgPresetBuiltIn"] = "Built-in presets cannot be overwritten. Choose a different name.",
                    ["Loc.MsgPresetBuiltInDelete"] = "Built-in presets cannot be deleted.",
                    ["Loc.MsgPresetReset"] = "Default presets have been reset.",
                    ["Loc.MsgResetConfirmTitle"] = "Confirm reset",
                    ["Loc.MsgResetConfirmMessage"] = "Are you sure you want to reset all default presets?\n\nThis action cannot be undone.",
                    ["Loc.ThemesResetDefaultsFull"] = "Reset default presets",
                    ["Loc.MsgRestoreError"] = "Error restoring windows:\n{0}",
                    ["Loc.MsgSaveError"] = "Error saving windows:\n{0}",
                    ["Loc.MsgMoveFolderError"] = "Folder could not be moved:\n{0}",
                    ["Loc.MsgMoveFileError"] = "File could not be moved:\n{0}",
                    ["Loc.MsgOpenFolderError"] = "Error opening folder:\n{0}",
                    ["Loc.MsgOpenFileError"] = "Error opening file:\n{0}",
                    ["Loc.MsgStartupError"] = "Autostart could not be updated:\n{0}",
                    ["Loc.PromptLayoutName"] = "Layout name",
                    ["Loc.PromptPanelName"] = "Panel name"
                }
            };

        private void ApplyLanguage(string? code)
        {
            string normalized = string.IsNullOrWhiteSpace(code) ? DefaultLanguageCode : code.Trim();
            if (!LocalizationData.ContainsKey(normalized))
            {
                normalized = DefaultLanguageCode;
            }

            CurrentLanguageCode = normalized;
            if (System.Windows.Application.Current?.Resources != null &&
                LocalizationData.TryGetValue(normalized, out var values))
            {
                foreach (var pair in values)
                {
                    System.Windows.Application.Current.Resources[pair.Key] = pair.Value;
                }
            }

            UpdateNotifyIconMenu();
        }

        public static string GetString(string key)
        {
            if (System.Windows.Application.Current?.Resources != null &&
                System.Windows.Application.Current.Resources.Contains(key))
            {
                return System.Windows.Application.Current.Resources[key]?.ToString() ?? key;
            }

            if (LocalizationData.TryGetValue(CurrentLanguageCode, out var values) &&
                values.TryGetValue(key, out var value))
            {
                return value;
            }

            return key;
        }
    }
}
