name: Bug report
description: Report a reproducible problem in DesktopPlus
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the bug?
      placeholder: A clear and concise description
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: App version
      placeholder: e.g. 1.0.0
    validations:
      required: true

  - type: input
    id: windows_version
    attributes:
      label: Windows version
      placeholder: e.g. Windows 11 24H2
    validations:
      required: true
